# 使用语言
language: node_js

sudo: false

# node版本
node_js:
  - "6"

# 设置只监听哪个分支
branches:
  only:
    - source

# 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
cache:
  yarn: true
  directories:
    - node_modules

# tarvis生命周期执行顺序详见官网文档
before_install:
  - npm install -g hexo-cli

install:
# 不用yarn的话这里改成 npm i 即可
  - yarn install --pure-lockfile

script:
  - hexo clean
  - hexo generate

after_success:
  - cd ./public
  - git config --global user.name "liwenguang"
  - git config --global user.email "liwenguang_dev@163.com"
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
# 这里的 REPO_TOKEN 即之前在 travis 项目的环境变量里添加的
  - git push --quiet --force https://${REPO_TOKEN}@github.com/LiWenGu/liwenguang.github.io master:publish